services:
  wsi-clean:
    build: .
    container_name: ui_clean
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/c/Users/piero/Documents/Data WSI:/data

  wsi-analysis:
    build: .
    container_name: ui_analysis
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/c/Users/piero/Documents/Data WSI:/data
    
    command: python ui_pyqt5.py