import glob
import json
import os
import time

import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from matplotlib.pyplot import imread
from PIL import Image

from src.config import CLASS_NAMES

# The thumbnail generated by ``StartAnalysis.get_thumb`` can exceed PIL's
# default 89 Mpx DecompressionBomb threshold when slow mode uses a fine
# OpenSlide level (e.g. ~120 Mpx). Raise the limit once at import so the
# legitimate, user-generated thumbnail is loaded without a noisy warning.
# We do NOT disable the limit entirely — a runaway gigapixel image is still
# flagged. The new limit is comfortably above any practical WSI thumbnail
# (~Reminder resolution).
Image.MAX_IMAGE_PIXELS = 250_000_000


class Classification:
    def __init__(self, path, ty):
        self.path = path
        self.ty = ty
        self.dictionary = {}
        self.np_list_image = []
        self.shape = (64, 64, 3)
        #self.select_folder()
        self.cl = list(CLASS_NAMES)

    def analysis_folder(self, sel_folder):
        """ Analyze the selected folder, finding all the png files"""

        list_files = glob.glob(sel_folder)
        n_elements = len(list_files)
        return list_files, n_elements

    def select_folder(self):
        """
        Create the dict with the key the number of the tile, to each key correspond another sub-dict that as key as
        'image' and value the path to the image.  At the same time it's created a list of numpy arrays that contain
        the image vectors already padded. Only the folder that start with 'p_' are analayzed, others are skipped.
        """
        self.dictionary = {}
        n_tile = 0
        list_image = []
        folders_tot = os.listdir(self.path)
        if self.ty == 'analysis':
            folders = [y for y in folders_tot if y[0:2] == 'p_']
        else:
            folders = ['/AC', '/H', '/AD']

        for i in folders:
            sel_folder = self.path + str(i) + '/*.png'
            list_files, n_elements = self.analysis_folder(sel_folder)
            for j in list_files:
                sub_d = {}
                complete_name = j[j.index('tile'):-4]
                partial = complete_name[complete_name.index('_') + 1:]
                tile_pos = partial[list(partial).index('_') + 1:]
                column = int(tile_pos[:list(tile_pos).index('_')])
                row = int(tile_pos[list(tile_pos).index('_')+1:])
                np_image, shape_x, shape_y = self.tile_control(j)
                if self.ty == 'datacleaning':
                    sub_d['name'] = j[j.index('pz_'):j.index('_tile')]
                    sub_d['true_class'] = i[1:]
                    n_tile += 1
                else:
                    n_tile = partial[:partial.index('_')]
                sub_d["im_path"], sub_d["shape_x"], sub_d["shape_y"], sub_d["col"], sub_d["row"] = j, shape_x, shape_y, column, row
                list_image.append(np_image)
                self.dictionary[n_tile] = sub_d
            print(f'Selected Folder:   {sel_folder:<40} Number of elements: {n_elements}   Total Images: {len(list_image)}')

        print(len(self.dictionary))
        self.np_list_image = np.asarray(list_image)

    def tile_control(self, j):
        """ This method read the image, modify it as numpy array and at the end control if same padding is needed."""
        np_image = imread(j)
        shape_i = np_image.shape
        if shape_i != self.shape:
            try:
                np_image = np.pad(np_image, ((0, self.shape[0] - shape_i[0]), (0, self.shape[1] - shape_i[1]), (0, 0)),
                                  'constant', constant_values=1)
            except ValueError:
                print(f'ATTENTION: error in the png file shape.\n Shape tile standard:{self.shape} '
                      f'\n Shape tile:{shape_i}')
        return np_image, shape_i[0], shape_i[1]

    def load_model(self, model_name):
        self.model = tf.keras.models.load_model(model_name)

    def classify(self, typean, monte_c, model_n, progress_callback, view=0):
        """
        Load the model and analyze the tile, the dictionary is updated with the predicted label
        """
        if not self.dictionary:
            # ``select_folder`` is not called by ``__init__``; invoke it here
            # so the tile dict and padded-image list are populated before the
            # model runs. Skipping this left ``np_list_image`` as a plain list
            # and crashed on ``np_list_image.shape`` below.
            self.select_folder()
        self.load_model(model_name=model_n)
        print(self.np_list_image.shape)
        tesu = []
        progress_callback.emit(1)
        mc = monte_c

        for i in range(0, mc):
            # The MC loop covers the first 0–80 % of overall analysis progress
            # (the remaining 80→100 % is taken by the four overlay() calls
            # below). Use int(...) so the emitted value is a plain Python int —
            # passing a float to a pyqtSignal(int) has produced garbage values
            # on some PyQt5 builds (huge or negative percentages).
            progress_callback.emit(int(80 * (i + 1) / mc))

            tesu.append(self.model.predict(self.np_list_image, batch_size=50))

        probs = np.asarray(tesu)
        clas_mean = np.mean(probs, axis=0)
        aleatoric = np.mean(probs * (1 - probs), axis=0)
        epistemic = np.mean(probs ** 2, axis=0) - np.mean(probs, axis=0) ** 2
        print(f'TESU: {len(tesu)} \n SHAPE EPI: {epistemic.shape} \n SHAPE ALE: {aleatoric.shape}')

        for i, y in enumerate(self.dictionary):
            self.dictionary[y]["pred_class"] = self.cl[int(np.argmax(clas_mean[i]))]
            self.dictionary[y]["epi"] = float(np.round(np.sum(epistemic[i]), 4))
            self.dictionary[y]["ale"] = float(np.round(np.sum(aleatoric[i]), 4))

        if typean == 'datacleaning':
            progress_callback.emit(100)
        else:
            self.overlay(typean)
            progress_callback.emit(80)
            self.overlay(typean, unc='epi')
            progress_callback.emit(90)
            self.overlay(typean, unc='ale')
            self.overlay(typean, unc='tot')
            progress_callback.emit(100)

        print('dictionary', len(self.dictionary))
        with open(os.path.join(self.path, 'dictionary_monte_' + str(monte_c) + '_js.txt'), 'w') as f:
            json.dump(self.dictionary, f, indent=4)

    def show_image(self, im):
        """GREAT NOTE: LIST ARE index-1 for the 0 index """
        plt.subplot(1, 3, 1)
        plt.imshow(self.np_list_image[76, :, :, :])
        plt.subplot(1, 3, 2)
        #plt.imshow(self.np_list_image[75, :, :, :])
        plt.imshow(im)
        plt.subplot(1, 3, 3)
        plt.imshow(self.np_list_image[74, :, :, :])
        plt.show()

    def overlay(self, typean, unc='Pred_class'):
        a = plt.imread(os.path.join(self.path, 'thumbnail', 'th.png'))
        image_base = np.zeros((a.shape[0], a.shape[1], 4), dtype=float)
        image_base_H = np.zeros((a.shape[0], a.shape[1], 4), dtype=float)
        image_base_AC = np.zeros((a.shape[0], a.shape[1], 4), dtype=float)
        image_base_AD = np.zeros((a.shape[0], a.shape[1], 4), dtype=float)

        print(f'IMAGE SHAPE BASE {image_base.shape}')
        # Compute per-tile footprint on the thumbnail so the overlay covers
        # the whole canvas instead of a small top-right patch. The grid
        # extents (max col/row + 1) come from the dictionary itself, so we
        # no longer rely on the hardcoded 64/4 = 16 step that assumed the
        # tile grid mapped 1:16 onto the thumbnail (true only for a very
        # specific lev_sec / DeepZoomGenerator combination).
        if self.dictionary:
            n_cols = max(v["col"] for v in self.dictionary.values()) + 1
            n_rows = max(v["row"] for v in self.dictionary.values()) + 1
        else:
            n_cols = n_rows = 1
        # Integer per-tile partition of the thumbnail canvas.
        # ``a.shape[0]`` is rows (y), ``a.shape[1]`` is cols (x). Using
        # ``floor(k*W/N)`` / ``floor((k+1)*W/N)`` guarantees that adjacent
        # cells share an exact integer boundary — no rounding drift, no
        # ~1px gaps, no ~1px overlaps. ``round(step*col)`` (the previous
        # approach) accumulated float drift across the grid.
        H, W = a.shape[0], a.shape[1]
        res_path = os.path.join(self.path, 'result')

        if not os.path.exists(res_path):
            os.makedirs(os.path.join(res_path, 'uncertainty'))

        if unc == 'Pred_class':
            res_name = [os.path.join(res_path, str(unc) + '.png'),
                        os.path.join(res_path, 'AC.png'),
                        os.path.join(res_path, 'H.png'),
                        os.path.join(res_path, 'AD.png')]
        else:
            res_name = os.path.join(res_path, 'uncertainty', str(unc) + '.png')

        n1, n2, n3 = 0, 0, 0

        for _i, name_t in enumerate(self.dictionary):

            u_tot = self.dictionary[name_t]["ale"]+self.dictionary[name_t]["epi"]
            column = self.dictionary[name_t]["col"]
            row = self.dictionary[name_t]["row"]
            # Compute exact integer cell rect for this tile on the thumbnail.
            # Rows (y) span [r0, r1), cols (x) span [c0, c1) — boundaries are
            # ``floor(k*size/N)`` so adjacent cells share an exact integer
            # edge (no gaps, no overlaps). Note: the row slice must use the
            # row-axis (H/step_y) size and the col slice the col-axis
            # (W/step_x) size; the previous code transposed them, which made
            # each cell non-square and shifted cells by a few px per step.
            r0 = (row * H) // n_rows
            r1 = ((row + 1) * H) // n_rows
            c0 = (column * W) // n_cols
            c1 = ((column + 1) * W) // n_cols
            if unc == 'Pred_class':
                clas = self.dictionary[name_t]["pred_class"]
                if clas == 'AC' and u_tot < 0.2:
                    # red
                    image_base[r0:r1, c0:c1, 0] += 1
                    image_base[r0:r1, c0:c1, 2] += 0.2
                    image_base_AC[r0:r1, c0:c1, 0] += 1
                    image_base_AC[r0:r1, c0:c1, 2] += 0.2

                    n1 += 1
                elif clas == 'H' and u_tot < 0.2:
                    # green
                    image_base[r0:r1, c0:c1, 1] += 0.95
                    image_base[r0:r1, c0:c1, 0] += 0.23
                    image_base_H[r0:r1, c0:c1, 1] += 0.95
                    image_base_H[r0:r1, c0:c1, 0] += 0.23
                    n2 += 1
                elif clas == 'AD' and u_tot < 0.2:
                    # blue
                    image_base[r0:r1, c0:c1, 2] += 0.9
                    image_base[r0:r1, c0:c1, 1] += 0.5
                    image_base_AD[r0:r1, c0:c1, 2] += 0.9
                    image_base_AD[r0:r1, c0:c1, 1] += 0.5
                    n3 += 1

            elif unc == 'epi':
                image_base[r0:r1, c0:c1, 2] += abs(self.dictionary[name_t]["epi"])
                image_base[r0:r1, c0:c1, 3] += abs(self.dictionary[name_t]["epi"])
            elif unc == 'ale':
                image_base[r0:r1, c0:c1, 2] += abs(self.dictionary[name_t]["ale"])
                image_base[r0:r1, c0:c1, 3] += abs(self.dictionary[name_t]["ale"])
            elif unc == 'tot':
                image_base[r0:r1, c0:c1, 2] += abs(u_tot)
                image_base[r0:r1, c0:c1, 3] += abs(u_tot)
            else:
                print(f'Strange command:{unc}')
                pass

        if unc == 'Pred_class':
            print(f'AC --> {n1:>4}\nH --> {n2:>4}\nAD --> {n3:>4}')
            print(n1 + n2 + n3)
            image_base[:, :, 3] = 0.3

            image_base_AC[:, :, 3] = 0.4
            rc, cc = np.where(image_base_AC[:, :, 0] < 0.2)
            image_base_AC[rc, cc, 3] = 0.1

            image_base_AD[:, :, 3] = 0.3
            rd, cd = np.where(image_base_AD[:, :, 2] < 0.2)
            image_base_AD[rd, cd, 3] = 0.1

            image_base_H[:, :, 3] = 0.3
            rh, ch = np.where(image_base_H[:, :, 1] < 0.2)
            image_base_H[rh, ch, 3] = 0.1

            list_im = [image_base, image_base_AC, image_base_H, image_base_AD]

            for im, name in enumerate(res_name, 0):
                self.new_save(list_im[im], name)
        else:
            if unc == 'tot' or unc == 'ale':
                r_h, c_h = np.where(image_base[:, :, 2] < 0.4)
                image_base[r_h, c_h, 2] = 0
                image_base[r_h, c_h, 3] = 0.1
                r_m, c_m = np.where((image_base[:, :, 2] < 0.5) & (image_base[:, :, 2] > 0.4))
                image_base[r_m, c_m, 3] = 0.2
            else:
                pass

            self.new_save(image_base, res_name)

    def new_save(self, image_base, res_name):
        image_base = np.where(image_base < 1, image_base, 1)
        background = Image.open(os.path.join(self.path, 'thumbnail', 'th.png'))
        foreground = Image.fromarray(np.uint8(image_base*255), mode='RGBA')
        background.paste(foreground, (0, 0), foreground)
        #background.show()
        background.save(res_name)

    def load_dict(self):
        name_f = os.path.join(self.path, 'dictionary_monte_50_js.txt')
        with open(name_f) as f:
            self.dictionary = json.load(f)


if __name__ == '__main__':

    t = time.perf_counter()
    sasa = Classification('D:/per_anamap_5_2/', ty='analysis')
    #sasa.show_image()
    #sasa.classify(typean='fast')
    sasa.load_dict()
    sasa.overlay(unc='Pred_class')
    t1 = time.perf_counter()

    s = t1-t
    print(s)
